apiVersion: skaffold/v4beta9
kind: Config

metadata:
  name: foobar

build:
  artifacts:
    - image: examples/foobar
      context: .

profiles:
  - name: issue1
    manifests:
      kustomize:
        paths:
          - kustomize/overlays/issue1/

  - name: issue2
    manifests:
      kustomize:
        paths:
          - kustomize/overlays/issue2/